### ISSUE TITLE
Display measurement results in GUI

### ISSUE THREAD

**Issue by gavv** [gavv/signal-estimator#13]
Currently GUI displays a plot with emitted and captured signals, but doesn't display actual measurements results (latency or loss ratio, depending on selected mode).

We should adjust GUI to:

* parse periodic measurements reports from tool output
* display and update current and average values in UI

The exact list of measurement results, depending on estimation mode, can be found in README.

If #30 will be done before this task, then there is no need to implement parsing code.

**Comment by Chinry** [comment]
I can take a look at this

**Comment by gavv** [comment]
@Chinry Great, thanks!

**Comment by gavv** [comment]
Landed
