### ISSUE TITLE
Display command-line and logs in GUI

### ISSUE THREAD

**Issue by gavv** [gavv/signal-estimator#16]
When you press start, GUI internally starts `signal-estimator` command-line tool with some options, which values depend on what you've configured in GUI.

It would be very convenient to display the resulting command line invocation, as well as `signal-estimator` logs (printed to stderr). I would allow the user to troubleshoot failures and/or reproduce measurements without GUI.

For example, we can add a text box to which we will print command-line and logs. We could place it into a separate tab, say, "Console" or "Logs".

**Comment by filbert14** [comment]
Hey! Can i claim this? :)

**Comment by gavv** [comment]
Hey, sure, you're welcome.

**Comment by gavv** [comment]
Not relevant because of #30.
