### ISSUE TITLE
Add JSON output support

### ISSUE THREAD

**Issue by gavv** [gavv/signal-estimator#2]
Steps:

* add a new interface IFormatter with methods like report_latency(...) and report_losses(...)
* add two implementations: TextFormatter (implementing the current output formatting) and JsonFormatter (implementing the new JSON formatting)
* use IFormatter in LatencyEstimator and LossEstimator  instead of raw call to se_log_info()
* add a command-line option that enables JSON formatter; it it's not specified, use text formatter by default

When JSON is enabled, this output:

```
latency:  sw+hw  13.145ms  hw   2.934ms  hw_avg5   2.934ms
latency:  sw+hw  12.465ms  hw   2.924ms  hw_avg5   2.929ms
...
```

should turn to something like this:

```
[
  {"sw+hw": 13.145, "hw": 2.934, "hw_avg5": 2.934},
  {"sw+hw": 12.465, "hw": 2.924, "hw_avg5": 2.929},
  ...
...
```

**Comment by BitsonFire** [comment]
Hi! I'm a beginner to open source contributions and I'd like to work on this issue. I had a doubt regarding the JSON formatting. Do you want to me to use an Json library like JsonCpp for doing that or would just printing it in JSON format be enough?
Thank You!

**Comment by gavv** [comment]
Hi, you're welcome.

I think for this small tool it would be enough to print JSON manually without any libraries, given that the format is simple and we never need to parse it, only format.

**Comment by gavv** [comment]
Merged.
