### ISSUE TITLE
Build failure on Alpine Linux

### ISSUE THREAD

**Issue by sodface** [gavv/signal-estimator#23]
Hello, I'm trying to package signal-estimator for Alpine Linux, I was originally going to just do a cli only package as I would probably not use the GUI, but I thought I might try to build it anyway and have a -gui subpackage. I am running into the following build error:

```
/srv/aports/repo/signal-estimator/src/signal-estimator-0.0.4/src/gui/MainWindow.cpp: In constructor 'MainWindow::MainWindow(QWidget*)':
/srv/aports/repo/signal-estimator/src/signal-estimator-0.0.4/src/gui/MainWindow.cpp:43:36: error: cannot convert 'QColor' to 'const QPen&'
   43 |     zoomInPicker->setRubberBandPen(QColor(Qt::red));
      |                                    ^~~~~~~~~~~~~~~
      |                                    |
      |                                    QColor
In file included from /usr/include/qwt/qwt_plot_picker.h:14,
                 from /srv/aports/repo/signal-estimator/src/signal-estimator-0.0.4/src/gui/MainWindow.hpp:18,
                 from /srv/aports/repo/signal-estimator/src/signal-estimator-0.0.4/src/gui/MainWindow.cpp:4:
/usr/include/qwt/qwt_picker.h:209:28: note:   initializing argument 1 of 'void QwtPicker::setRubberBandPen(const QPen&)'
  209 |     void setRubberBandPen( const QPen& );
      |                            ^~~~~~~~~~~
```

**Comment by marco-langer** [comment]
Which version of Qt and Alpine Linux? It looks odd, because the implicit QPen constructor from a QColor has not changed in the last years as far as I can see in Qt's git repository.

**Comment by sodface** [comment]
Thanks for the reply. By local build machine is on Alpine 3.16.0 (latest-stable) but I did have to add the edge/testing repo for qwt-dev so that might be the issue. I will push a draft MR and see if Alpine's CI/CD passes since it should be using all edge package versions. I will post back.

madedepends versions are:

alsa-lib-dev (1.2.6.1-r0)
cmake (3.23.1-r0)
cxxopts-dev (3.0.0-r0)
qt5-qtbase-dev (5.15.5_git20220619-r0)
qwt-dev (6.2.0-r0)

The meat of the APKBUILD is:

```
makedepends="
        alsa-lib-dev
        cmake
        cxxopts-dev
        qt5-qtbase-dev
        qwt-dev
        "
build() {
        cmake -B build \
                -DCMAKE_BUILD_TYPE=MinSizeRel \
                -DCMAKE_INSTALL_PREFIX=/usr
        cmake --build build
}

package() {
        DESTDIR="$pkgdir" cmake --install build
}
```

**Comment by marco-langer** [comment]
I am not quite sure but I don't think the error is related to qwt, because the error message says it is due to an error in the Qt library: `cannot convert 'QColor' to 'const QPen&'`.

However, I have difficulties to follow because the build uses Qt. 5.15.5, which is a commercial LTS version for which I don't have access to. I can't even find a public changelog for anything after 5.15.2.

Can you please check in the file `qtbase/src/gui/qpen.h` if this constructor is still available:

https://github.com/qt/qtbase/blob/73e1bc09e63394490d91a223b3479b46c1595d66/src/gui/painting/qpen.h#L29

**Comment by sodface** [comment]
Hi, thanks, yes that entry is present in qpen.h. Just before you replied, I was able to get my local build to complete successfully with the below patch. I also installed and tested it and the GUI is displayed.

```
--- ./src/gui/MainWindow.cpp.orig
+++ ./src/gui/MainWindow.cpp
@@ -6,6 +6,7 @@
 #include "ui_MainWindow.h"
 
 #include <QCheckBox>
+#include <QPen>
 
 #include <qwt_legend.h>
 #include <qwt_picker_machine.h>
@@ -40,7 +41,7 @@
     QwtPlotPicker* zoomInPicker = new QwtPlotPicker(ui->OutputSig->canvas());
     zoomInPicker->setStateMachine(new QwtPickerDragRectMachine());
     zoomInPicker->setRubberBand(QwtPicker::RectRubberBand);
-    zoomInPicker->setRubberBandPen(QColor(Qt::red));
+    zoomInPicker->setRubberBandPen(QPen(QColor(Qt::red)));
     connect(zoomInPicker, qOverload<const QRectF&>(&QwtPlotPicker::selected),
         [this](const QRectF& rect) {
             ui->OutputSig->setAxisScale(

```

**Comment by marco-langer** [comment]
That's great :-). Are you gonna submit a pull request with the change or should I do it?

**Comment by gavv** [comment]
Thanks, PR is merged!

> I can start and stop again and the window never exits, it's just clicking stop always results in the "Process crashed" message.

Yep, this is a known issue, I didn't try to investigate it yet. It's mentioned here #14.

**Comment by sodface** [comment]
Thank you for the feedback and merge to fix the build. Packages available now in Alpine testing repo:
https://pkgs.alpinelinux.org/packages?name=signal-estimator&branch=edge
