### ISSUE TITLE
Switch to spdlog

### ISSUE THREAD

**Issue by gavv** [gavv/signal-estimator#38]
- [x] Add [spdlog](https://github.com/gabime/spdlog) submodule to `3rdparty/` dir.
- [x] Add spdlog to `cmake/ThirdParty.cmake`.
- [x] Switch macros `core/Log.hpp` from fprintf() to spdlog.
- [x] Rework all invocations of `se_log_*()` macros to use `{fmt}` instead of printf format strings.
- [x] Initialize spdlog at program start, use asynchronous logger.

**Comment by aadit-n3rdy** [comment]
Hey! May I work on this issue?

**Comment by gavv** [comment]
Sure, thanks!
