### ISSUE TITLE
Add graphical user interface

### ISSUE THREAD

**Issue by gavv** [gavv/signal-estimator#6]
## Overview

Often, when debugging using signal-estimator, you need a visual inspection of input and output streams of samples.

Currently signal-estimator is a command-line tool. The visual inspection is possible by dumping streams to files and then plotting them using, e.g., matplotlib.

However, in many cases, it would be extremely handy to inspect stream in real-time. So we could go one step further and implement UI to signal-estimator allowing to do that.

Here is how I see it:

```
SETTINGS:
┌──────────────────┐    ┌──────────────────┐
│   input device ▼ │    │  output device ▼ │
└──────────────────┘    └──────────────────┘
┌──────────────────┐
│           mode ▼ │
└──────────────────┘
┌──────────────────┐
│    sample rate   │    < other settings >
└──────────────────┘

CONTROL:
┌─────────┐  ┌─────────┐
│  START  │  │   STOP  │
└─────────┘  └─────────┘

INPUT SIGNAL:
┌────────────────────────────────────┐
│              /\    /\    /\    /\  │
│............/    \/    \/    \/    \│
└──────────────────── ───────────────┘

OUTPUT SIGNAL:
┌────────────────────────────────────┐
│              /\    /\    /\    /\  │
│............/    \/    \/    \/    \│
└──────────────────── ───────────────┘
```

Here, the UI have three parts:

* various settings, replicating existing command-line options
* start / stop buttons
* real-time plots with input and output streams

They key point here is real-time plots, in particular the visualization method we choose for them. I suggest to try sliding window. We start with an empty plot. A new point is added to the right, and when it's added, all earlier added points shift to the left. Probably we'll want different visualization options.

## Implementation notes

* I suggest to use Qt + Qwt. Qt is C++-friendly and will make it easy to port signal-estimator to non-Linux platforms in future. Qwt is a great library for plotting.

* I think the UI should be implemented in a separate executable, say, `signal-estimator-qt`.

* It should be possible to disable building UI, and thus disable Qt dependency, at compile time (using CMake option).

* The UI should work in a separate thread and shouldn't be able to block audio threads.

* The implementation can be split into multiple PRs. For example, we can start with a simple UI prototype without plots, merge it, and the incrementally review and merge more features.

**Comment by ndcroos** [comment]
Hello, I would like to work on this issue.

**Comment by gavv** [comment]
@ndcroos You're welcome!

**Comment by ndcroos** [comment]
@gavy Should the input and output device controls be comboboxes that are populated with options that are retrieved from the underlying operating system?

**Comment by gavv** [comment]
> Should the input and output device controls be comboboxes that are populated with options that are retrieved from the underlying operating system?

Ideally, yes, we should retrieve device list from ALSA and later also from PulseAudio (#1). However, I think in the very first version we can choose a simpler implementation, e.g. just textboxes.

**Comment by Vhuynh25** [comment]
Hi do you mind if I work on this issue too?

**Comment by gavv** [comment]
@ndcroos Hi, do you have any progress / plans on this?

**Comment by ndcroos** [comment]
@gavv Sorry, I lost track of this. I did not get far with this issue. I also had troubles using Qwt from Qt Designer UI. I guess it is best that @Vhuynh25 starts from a blank slate.

**Comment by gavv** [comment]
@ndcroos no worries. @Vhuynh25 you're welcome than :)

**Comment by Vhuynh25** [comment]
ok so I'll start asking questions for problems when I run into them. 

First off, I'm using Qspinboxes to get the value for the signal-estimator options but each spinbox needs a maximum value.
So gavv what maximum value should I set for each option.

**Comment by gavv** [comment]
I don't think we really have any reasonable maximum value for most of the options, so likely we need another widget for them. There are some options which have value from 0 to 1, but they are floats, so it seems they need another widget as well.

**Comment by Vhuynh25** [comment]
If there is no maximum value, then I'll just set to it to the maximum that an int or a double can hold.
I'll switch to Qdoublespinboxes for the float options.

**Comment by gavv** [comment]
Yes, in other words we want to plot on fly the amplitude of the signal sent and received from devices.

**Comment by Vhuynh25** [comment]
@gavv hey I put up a pull request a while ago and would like some feedback but you're too busy to review my work, just drop a quick comment saying so.

**Comment by gavv** [comment]
@Vhuynh25 Thanks for your work and sorry for delay! I'm currently reviewing the PR and will leave feedback soon.

**Comment by gavv** [comment]
First version landed!
