### ISSUE TITLE
Add simple unit tests

### ISSUE THREAD

**Issue by gavv** [gavv/signal-estimator#8]
Currently we have no unit tests at all.

For some of the components developing a correct test wouldn't be trivial. However we can at least start with adding tests for a few components that can be covered easily:

- [x] MovMax
- [x] MovAvg
- [x] MovDev
- [x] MovGradient
- [x] MovPercentile
- [x] SchmittTrigger

I suggest to implement tests using Google Test library. We'll have to add it to 3rdparty directory as a submodule and add to CMake like we do it here: https://github.com/roc-streaming/rt-tests/blob/master/CMakeLists.txt#L5-L25

We should also add test step to CI.

**Comment by saneck2150** [comment]
Can i try to do this task?

**Comment by gavv** [comment]
You're welcome :)

**Comment by gavv** [comment]
Landed.
